deployment:
  tasks:
    - export DEPLOYPATH=/home/bekuexpr/public_html/comercialweb.cl/wp-content/plugins/dokan/modules/store-support/
    - /bin/cp module.php $DEPLOYPATH
    - export DEPLOYPATH=/home/bekuexpr/public_html/comercialweb.cl/wp-content/plugins/dokan/modules/store-support/assets/js/
    - /bin/cp script.js $DEPLOYPATH
