---
deployment:
  tasks:
    - export DEPLOYPATH=public_html/comercialweb.cl
    - /bin/cp /wp-content/plugins/dokan/modules/store-support/module.php $DEPLOYPATH
    - /bin/cp /wp-content/plugins/dokan/modules/store-support/assets/js/script.js $DEPLOYPATH
