---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bekuexpr/public_html/comercialweb.cl/wp-content
    - /bin/cp module.php $DEPLOYPATH
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bekuexpr/public_html/comercialweb.cl/wp-content/plugins/dokan/modules/store-support/assets/js
    - /bin/cp script.js $DEPLOYPATH
